version: '3.3'
services:
  catalogue:
    container_name: catalogue
    image: wellcome/catalogue_webapp:${CONTAINER_TAG:-test}
    build:
      context: ../..
      dockerfile: ./catalogue/webapp/Dockerfile
    ports:
      - "3000:3000"
